popup_enabled:
  type: bool
  default: false
  description:
    en: "Enable the event popup"
content_text:
  type: string
  default: "Catch us next at the upcoming community event happening 21 March"
  description:
    en: 'Text for the event banner.'
button_text:
  type: string
  default: "Join us"
  description:
    en: 'Button text for the event banner.'
content_text_color:
  type: string
  default: "#000000"
  description:
    en: 'Text color as #RRGGBB for the content.'
content_background_color:
  type: string
  default: "#ffffff"
  description:
    en: 'Text color as #RRGGBB for the background.'
button_text_color:
  type: string
  default: "#ffffff"
  description:
    en: 'Text color as #RRGGBB for the button.'
button_background_color:
  type: string
  default: "#6161ff"
  description:
    en: 'Background color as #RRGGBB for the button.'
button_link:
  type: string
  default: "/"
  description:
    en: 'Button Link for the event banner.'
update_version:
  type: string
  default: "20230401"
  description:
    en: "Increase this version if you want to make the banner reappear for the people that closed it."
countdown_to:
  type: string
  default: ""
  description:
    en: "Countdown to, as YYYY-MM-DD HH:MM (UTC time)"
countdown_digits_font_size:
  type: float
  default: 1.5
  description:
    en: "Font size in em for countdown digits"
countdown_digits_color:
  type: string
  default: "#cccccc"
  description:
    en: "Color as #RRGGBB for countdown digits"
background_image_desktop_url:
  type: string
  default: ""
  description:
    en: "Background image URL for desktop"
popup_height_desktop:
  type: integer
  default: 0
  description:
    en: "Height of the popup in pixels for desktop (0 = auto for text). For background calculate aspect ratio for 500px wide."
popup_width_desktop:
  type: integer
  default: 500
  description:
    en: "Width of the popup in pixels for desktop (0 = auto)"
button_top_desktop:
  type: integer
  default: 0
  description:
    en: "Vertical adjustment for button (desktop)"
countdown_timer_top_desktop:
  type: integer
  default: 0
  description:
    en: "Vertical adjustment for countdown timer (desktop)"
countdown_timer_digit_width_desktop:
  type: integer
  default: 50
  description:
    en: "Digit width in px for countdown timer (desktop)"
background_image_mobile_url:
  type: string
  default: ""
  description:
    en: "Background image URL for mobile"
popup_height_mobile:
  type: integer
  default: 0
  description:
    en: "Height of the popup in pixels for mobile (0 = auto)"
popup_width_mobile:
  type: integer
  default: 500
  description:
    en: "Width of the popup in pixels for mobile (0 = auto)"
button_top_mobile:
  type: integer
  default: 0
  description:
    en: "Vertical adjustment for button (mobile)"
countdown_timer_top_mobile:
  type: integer
  default: 0
  description:
    en: "Vertical adjustment for countdown timer (mobile)"
countdown_timer_digit_width_mobile:
  type: integer
  default: 50
  description:
    en: "Digit width in px for countdown timer (mobile)"
cookie_name:
  type: string
  default: "event_popup_closed"
  description:
    en: "Name of cookie that remembers when popup is closed. Change only when you have this theme installed multiple times."